AllCops:
  Exclude:
    - 'spec/**/*'
    - 'tmp/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: true
  Max: 20
Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false