AllCops:
  Exclude:
    - 'tmp/**/*'
    # For  to avoid Lint/Syntax error on ruby embedded code.
    - 'lib/generators/sp-rails-saml/templates/create_saml_settings.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 170
Metrics/AbcSize:
  Enabled: false
Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/ClassVars:
  Exclude:
    - 'spec/**/*'
