AllCops:
  Exclude:
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'lib/generators/sp-rails-saml/templates/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/AbcSize:
  Enabled: false
Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/MethodLength:
  Max: 20