name: sp-rails-saml

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:2.6

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        run: |
          gem install bundler
          bundle install

      - name: Test
        run: bundle exec rake
