name: sp-rails-saml

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:2.6

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: gem intall bundler

      - name: Install dependencies
        run: bundle install

      - name: Test
        run: bundle exec rake
